/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PskFeedbackView {
    'typeOfAlert': string;
  }
  interface PskListFeedbacks {
    'hour': number;
    'messagesToDisplay': number;
    'minute': number;
    'second': number;
  }
  interface PskUiFeedback {
    'message': any;
    'timeMeasure': string;
    'timeSinceCreation': number;
    'typeOfAlert': string;
  }
}

declare global {


  interface HTMLPskFeedbackViewElement extends Components.PskFeedbackView, HTMLStencilElement {}
  var HTMLPskFeedbackViewElement: {
    prototype: HTMLPskFeedbackViewElement;
    new (): HTMLPskFeedbackViewElement;
  };

  interface HTMLPskListFeedbacksElement extends Components.PskListFeedbacks, HTMLStencilElement {}
  var HTMLPskListFeedbacksElement: {
    prototype: HTMLPskListFeedbacksElement;
    new (): HTMLPskListFeedbacksElement;
  };

  interface HTMLPskUiFeedbackElement extends Components.PskUiFeedback, HTMLStencilElement {}
  var HTMLPskUiFeedbackElement: {
    prototype: HTMLPskUiFeedbackElement;
    new (): HTMLPskUiFeedbackElement;
  };
  interface HTMLElementTagNameMap {
    'psk-feedback-view': HTMLPskFeedbackViewElement;
    'psk-list-feedbacks': HTMLPskListFeedbacksElement;
    'psk-ui-feedback': HTMLPskUiFeedbackElement;
  }
}

declare namespace LocalJSX {
  interface PskFeedbackView extends JSXBase.HTMLAttributes<HTMLPskFeedbackViewElement> {
    'onShowBadFeedback'?: (event: CustomEvent<any>) => void;
    'onShowGoodFeedback'?: (event: CustomEvent<any>) => void;
    'typeOfAlert'?: string;
  }
  interface PskListFeedbacks extends JSXBase.HTMLAttributes<HTMLPskListFeedbacksElement> {
    'hour'?: number;
    'messagesToDisplay'?: number;
    'minute'?: number;
    'onOpenFeedback'?: (event: CustomEvent<any>) => void;
    'second'?: number;
  }
  interface PskUiFeedback extends JSXBase.HTMLAttributes<HTMLPskUiFeedbackElement> {
    'message'?: any;
    'onCloseFeedback'?: (event: CustomEvent<any>) => void;
    'timeMeasure'?: string;
    'timeSinceCreation'?: number;
    'typeOfAlert'?: string;
  }

  interface IntrinsicElements {
    'psk-feedback-view': PskFeedbackView;
    'psk-list-feedbacks': PskListFeedbacks;
    'psk-ui-feedback': PskUiFeedback;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


